version: "2.2"
services:
  django:
    container_name: vycontrol
    build:
      context: .
      dockerfile: Dockerfile
    image: vycontrol
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
